### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by jeffersondanielss** [walbinjr/overtime-ng#1]
Eu fiz um teste aqui com o pkg [gh-pages](https://www.npmjs.com/package/gh-pages), pra depois que você rodar o `builld` para gerar a pasta dist na master, deixar um script pra rodar um `npm run deploy`  e ele já sobe essa pasta dist na branch `gh-pages`, mas só deu certo alterando a url base do index de:
```html
<base href="/">
```
para

```html
<base href="./">
```

Porque como estava antes no gh-pages estava pegando um caminho relativo errado, tem problema?
se não faço um PR ai :+1:

[Preview](https://jeffersondanielss.github.io/overtime-ng/)

**Comment by walbinjr** [comment]
Cara, vc resolveu 2 problemas! Esse do path relativo eu estava trocando na mão para:
```html
<base href="/overtime-ng/">
```
Pode fazer o PR
